language: python

git:
  autocrlf: input

install: pip install -U tox
script: tox -v

_anchors:
  - &refreshpath eval $(powershell -NonInteractive -Command 'write("export PATH=`"" + ([Environment]::GetEnvironmentVariable("PATH","Machine") + ";" + [Environment]::GetEnvironmentVariable("PATH","User")).replace("\","/").replace("C:","/c").replace(";",":") + ":`$PATH`"")')

jobs:
  include:
    - stage: test
      os: windows
      language: shell
      before_install:
        - choco install openjdk python3
        - *refreshpath
        - python --version
        - pip --version
        - java -version
      env: TOXENV=py3
    - os: osx
      language: shell
      env: TOXENV=py3
    - python: 3.5
      env: TOXENV=py
    - python: 3.6
      env: TOXENV=py
    - python: 3.7
      env: TOXENV=py
    - python: 3.8
      env: TOXENV=py
    - python: 3.5
      env: TOXENV=lint
    - python: 3.7
      env: TOXENV=eslint
      before_install:
        - sudo apt-get install npm
        - sudo npm install -g npx
    - python: 3.6
      env: TOXENV=docs

    - stage: deploy
      python: 3.5
      install: skip
      script: skip
      deploy:
        provider: pypi
        user: renatahodovan
        password:
          secure: yZ+6IWtgS0t0AhP8TCZCPAlZ/ZhY1kLCE95U67bFfWd2ofudW1MhGOEcml3y3L+dWyeWd4gZw53P+z33u24YNCZjYma7g1qRfANg362aR+zCXR4gbn+iCRpr4AT916NmDq3eYE4n+mfqLpg1Wu8qZFaRBY4g/yJhL3vl9/raXfG1Hg0ncULV8Jl7tg3JEwzl6NZ03kl2hk5XnHtLPQMjruhdbPlSWdur+zrqshj0iLT47dQ9aYFk4fyvc7hd2CWBqfsHLY0vavx0Mx+71CAN2h1dO0EUcg7mweTo7W3Q9gcXdosVwNqoPjRcagdmbNNBrWIx5w7trbxwaD4c0/9VA8QPpRjC8jlISZpb6kH0DT9ZpEbXMfKY1NX6nKJboy/qf3gr40Cd/0iow9ZlZAyuXebGh1chTFz/dNeIY/zkBC/eDuuH8X6YMBb8k8H/CrI9P+hitVjbSU2CKCOB+SL+8BsG8YcU6YEiQ5Xgu/jrKnr/Yuj1eQ48shxPypnbokkkLARz0GNPf3aolDp99EnZ6lxki7oKJRbXti72zN53T3jIviJ2+6aWC81MRFvqgy1YcABbKN4VUrwZgo0cczUuPpGBuIO7Cbk/LSygmkmLuJrIg+5M9C3GmOMSdI/pruQSFFhaQjX3X34SU4zySvmUsmZk0bA8eAStGO9zVl38p98=
        on:
          repo: renatahodovan/fuzzinator
          tags: true

# TODO: start mongodb once more complex tests are implemented
# services: mongodb
